version: 2
distribution_spec:
  description: CI tests for Llama Stack
  providers:
    inference:
      - provider_type: remote::vllm
      - provider_type: inline::sentence-transformers
    vector_io:
      - provider_type: inline::milvus
      - provider_type: remote::pgvector
    safety:
      - provider_type: inline::llama-guard
    agents:
      - provider_type: inline::meta-reference
    telemetry:
      - provider_type: inline::meta-reference
    eval:
      - provider_type: inline::meta-reference
    scoring:
      - provider_type: inline::basic
      - provider_type: inline::llm-as-judge
      - provider_type: inline::braintrust
    tool_runtime:
      - provider_type: remote::brave-search
      - provider_type: remote::tavily-search
      - provider_type: inline::rag-runtime
      - provider_type: remote::model-context-protocol
  container_image: registry.access.redhat.com/ubi9:latest
image_type: container
image_name: ubi9-test
additional_pip_packages:
  - aiosqlite
  - asyncpg
  - sqlalchemy[asyncio]
  - pymilvus
